language: cpp
dist: bionic
os:
 - linux
script:
 - mkdir build
 - cd build
 - cmake ../core
 - make -j10
 - cd ..
 - mkdir build-test && cd build-test
 - cmake ../test/runners/generic/
 - make
 - ./ReaderTest
